version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  working_directory: /DEPLOY-$(date +%Y-%m-%d)/
  build-and-deploy:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      
      # install dependcies in the requirement.txt using pip as a package manager
      - run:
          name: Install Requirement dependencies
          command: |
            pip install -r requirements.txt 

      
      - run:  # Run pytest testing script
          name: Run Pytest Tests
          command: |
            pytest  
      
      - run:  # Run unittest testing script
          name: Run Unittest Tests
          command: |
            python3 -m unittest test/calculator_unittest.py 

      - run: # check aws and pip version
            name: Check  aws version 
            command: |
              aws --version \
              && pip --version
            # && aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID \
      
      - run:  # Run coverage testing script
          name: Generating coverage report
          command: |
            coverage report -i calc/calculator.py

      - run: # Docker build image: circleci-docker-aws-tag
          name: Build application Docker image
          command: |
            docker build .



workflows:
  version: 2
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main  # build when commit / push to main branch

