# version: 2.1
# orbs:
#   python: circleci/python@1.5.0
# jobs:
#   build:
#     executor: python/default
#     steps:
#       - checkout
#       - python/install-packages:
#           pkg-manager: pip
#       - python/install-packages:
#           pip-dependency-file: requirements.txt
#           pkg-manager: pip
#       - python/install-packages:
#           args: pytest pytest-cov
#           pkg-manager: pip
#           pypi-cache: false
#       - run:
#           command: |
#             pytest coverage report
#           name: Test
# workflows:
#   main:
#     jobs:
#       - build


version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-deploy:
    executor: python/default

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
        
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt pytest pytest-cov

      - run:
          name: Run tests
          command: |
            pytest

      - run:
          name: Run coverage report
          command: |
            coverage report

      - run:
          name: Build artifacts and deploy
          command: |
            # Make a folder
            mkdir -p "DEPLOY-$(date +%Y-%m-%d)"
            cp -R dist/ "DEPLOY-$(date +%Y-%m-%d)/"

      - run:
          name: Deploy
          command: |
            # Replace this command with your deployment process
            echo "I am deploying now... :) "

workflows:
  version: 2
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main

