version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-deploy:
    executor: python/default

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
        
      - run:
          name: Install Requirement dependencies
          command: |
            pip install -r requirements.txt 

      - run:
          name: Install Coverage dependencies
          command: |
            python3 -m pip install coverage

      - run:
          name: Run Pytest Tests
          command: |
            pytest 
      - run:
          name: Run Unittest Tests
          command: |
            python3 -m unittest test/calculator_unittest.py 

      - run:
          name: Generating coverage report
          command: |
            # generate a report
            coverage report -i calc/calculator.py

      - run:
          name: Building artifacts and deploy
          command: |
            # Make a folder
            mkdir -p "DEPLOY-$(date +%Y-%m-%d)"
            cp -R dist/ "DEPLOY-$(date +%Y-%m-%d)/"

      - run:
          name: Deploy
          command: |
            # Deploying spinning now
            echo "I am deploying now... :) "

workflows:
  version: 2
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main

