version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  working_directory: /dist/DEPLOY-$(date +%Y-%m-%d)/
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      
      # install dependcies in the requirement.txt using pip as a package manager
      - run:
          name: Install Requirement dependencies
          command: |
            pip install -r requirements.txt 

      
      - run:  # install coverage from the script here, not from requirement.txt - an alternative
          name: Install Coverage dependencies
          command: |
            python3 -m pip install coverage

      
      - run:  # Run pytest testing script
          name: Run Pytest Tests
          command: |
            pytest 

      
      - run:  # Run unittest testing script
          name: Run Unittest Tests
          command: |
            python3 -m unittest test/calculator_unittest.py 

      - run: # check aws version
            name: Check  aws version 
            command: aws --version 

      - run: # check pip version
            name: Check  pip version 
            command: pip --version

      
      - run:  # Run coverage testing script
          name: Generating coverage report
          command: |
            # generate a report
            coverage report -i calc/calculator.py

      


      - run: # Docker build
          name: Build application Docker image
          command: |
            docker build -t circleci-docker-aws-tag .

      

      - run:
          name: Run docker check and tests
          command: |
            docker-compose -f ./docker-compose.test.yml up

      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "main" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi




      # # Build the Docker image
      # - setup_remote_docker:
      #     version: 22.0.0

      # - run:
      #     name: Build Docker image
      #     command: docker build -t dayogreats/your-repo:tag .

      # # Log in to Docker Hub
      # - run:
      #     name: Log in to Docker Hub
      #     command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # # Push the Docker image to Docker Hub
      # - run:
      #     name: Push Docker image to Docker Hub
      #     command: docker push your-username/your-repo:tag


      # - run: # Deploy heads up message.
      #     name: Deploy message
      #     command: |
      #       echo "Now deploying... :) "
          
      # - run: # Deploy to ec2 using the awscli command
      #       name: Deploy to S3
      #       command: aws ec2 sync <path/to/bucket> <s3://location/in/S3-to-deploy-to>

workflows:
  version: 2
  main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main  # build when commit / push to main branch





# /////////////

